### ISSUE TITLE
about the dataset

### ISSUE THREAD

**Issue by Hui-Yao** [vevenom/RoomLayout3D_RandC#3]
Hello, @vevenom 
Thanks for your impressive work of this project .
I`m working on my idea based on ScanNet-layout, and i need to annotate some custom pictures manually. 
So I wonder if you can send me the tagging tools or just tell me the name of these tools ?
Thanks a lot .

HuiYao

**Comment by vevenom** [comment]
Hi @Hui-Yao 

Thank you for the nice words.
Unfortunately I cannot share this part of the code but it's a fairly simple procedure.

If you are looking to annotate 2D polygons you can do that with [LabelMe](https://github.com/wkentaro/labelme) for example. For the 3D annotations we actually just drew 2D masks of planar layout surfaces. Then, for each of the annotated 2D layout polygons, we estimate plane parameters from the contained planar layout surfaces by relying on the associated depth map and a RANSAC procedure. From there, you can calculate the pixelwise layout depth.

**Comment by Hui-Yao** [comment]
Thanks a lot. Wish luck in your research.
