### ISSUE TITLE
How should I generate mseg confidence?

### ISSUE THREAD

**Issue by chytsa** [vevenom/RoomLayout3D_RandC#4]
Hi, I wonder how to generate the mseg prediction confidence for my own images?

To my knowledge and experience, MSEG network only generates gray scale segmentation result, I can't find confidence part. Could you tell me how to get the confidence?

Thank you very much.

**Comment by chytsa** [comment]
Oh, I have found the way to output confidence.

**Comment by soumyadipm** [comment]
@chytsa Confused with mseg confidence. Can you please help me regarding the same?

**Comment by chytsa** [comment]
> @chytsa Confused with mseg confidence. Can you please help me regarding the same?

you need to modify mseg segmentation network by yourself.
when the network call arg max function to get the estimated class, you also need to return confidence score for the estimated class.
this confidence score is mseg confidence.
hope this will help you: )

**Comment by soumyadipm** [comment]
Thanks a lot @chytsa. Now I am able to generate the confidence image.

**Comment by marcomiglionico94** [comment]
Hi guys I am trying to get the mseg confidence. I found the line of code in which they do argmax to get the estimated class. The main problem is that, that Tensor has shape (1080, 1920,194). So how do I get the confidence score ? I was thinking of using just max? Is it correct? 

> > @chytsa Confused with mseg confidence. Can you please help me regarding the same?
> 
> you need to modify mseg segmentation network by yourself. when the network call arg max function to get the estimated class, you also need to return confidence score for the estimated class. this confidence score is mseg confidence. hope this will help you: )

**Comment by chytsa** [comment]
@marcomiglionico94 Yes, you just need to use max, make sure you do on the right dim. Remember to return it back.
